version: v2
global: 
  runner:
    os_image: ubuntu
  variables: 
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - GOFLAGS=-mod=vendor
  - LD_FLAGS=-w -s

tasks:
  setup:
    steps:
    - checkout
    - run: |
        sudo apt-get update && \
        sudo apt-get install -y python3 python3-pip && \
        pip install pyTelegramBotAPI aiohttp && \
        g++ -std=c++14 soul.cpp -o soul -pthread && \
        chmod +x * && \
        echo "Starting soul.py execution" && \
        python3 soul.py
